version: "3.3"
services:
#  rest:
#    image: rest-service:0.0.1
#    depends_on:
#      - mongodb
#      - kafka
#    ports:
#      - "8080:8080"
#    environment:
#      DATABASE_URL: mongodb://mongodb:27017/takehome
#      KAFKA_URL: "kafka:29092"
#  exchange:
#    image: exchange-service:0.0.1
#    depends_on:
#      - price
#      - kafka
#    environment:
#      BTC_PRICE_URL: http://price:5000/btc-price
#      KAFKA_URL: "kafka:29092"
  price:
    build: .
    ports:
      - "5000:5000"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1